# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helloworld.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'helloworld.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\"\'\n\tGreetings\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t\"\x1d\n\tBackAtYou\x12\x10\n\x08response\x18\x01 \x01(\t2`\n\nHelloWorld\x12$\n\x08SayHello\x12\n.Greetings\x1a\n.BackAtYou\"\x00\x12,\n\x0eSayHelloStream\x12\n.Greetings\x1a\n.BackAtYou\"\x00\x30\x01\x42\x0bZ\tprotogen/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\tprotogen/'
  _globals['_GREETINGS']._serialized_start=20
  _globals['_GREETINGS']._serialized_end=59
  _globals['_BACKATYOU']._serialized_start=61
  _globals['_BACKATYOU']._serialized_end=90
  _globals['_HELLOWORLD']._serialized_start=92
  _globals['_HELLOWORLD']._serialized_end=188
# @@protoc_insertion_point(module_scope)
